[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "xpile"
version = "0.0.1"
description = "A Databricks (Spark SQL) transpiler"
readme = "README.md"
requires-python = ">= 3.11"
dependencies = [
   "databricks-labs-remorph==0.9.0",
   "pyspark==3.5.4",
   "databricks-sdk==0.44.1",
   "databricks-labs-lsql==0.14.1",
   "sqlglot"
]
authors = [
  {email = "will.girten@databricks.com"},
]
keywords = ["Databricks", "Spark"]

